//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyManager.Model.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoneyManager.Model.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nahrungsmittel.
        /// </summary>
        internal static string DefaultCategory_Food {
            get {
                return ResourceManager.GetString("DefaultCategory_Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hobby.
        /// </summary>
        internal static string DefaultCategory_Hobby {
            get {
                return ResourceManager.GetString("DefaultCategory_Hobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versicherung.
        /// </summary>
        internal static string DefaultCategory_Insurance {
            get {
                return ResourceManager.GetString("DefaultCategory_Insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechnung.
        /// </summary>
        internal static string DefaultCategory_Payment {
            get {
                return ResourceManager.GetString("DefaultCategory_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krankenkasse.
        /// </summary>
        internal static string DefaultCategory_Surgery {
            get {
                return ResourceManager.GetString("DefaultCategory_Surgery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datei {0} ist bereits in Benutzung. Bitte prüfen Sie, dass keine anderen MoneyManager-programme offen sind..
        /// </summary>
        internal static string ErrorLockingFile {
            get {
                return ResourceManager.GetString("ErrorLockingFile", resourceCulture);
            }
        }
    }
}
