//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyManager.ViewModels.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoneyManager.ViewModels.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontodatei (*.mmdb)|*.mmdb|Alle Dateien (*.*)|*.*.
        /// </summary>
        public static string AccountManagementFilterOpenAccount {
            get {
                return ResourceManager.GetString("AccountManagementFilterOpenAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mein Konto.
        /// </summary>
        public static string AccountManagementMyAccountDefaultName {
            get {
                return ResourceManager.GetString("AccountManagementMyAccountDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Konto.
        /// </summary>
        public static string AccountManagementPage_DefaultAccountName {
            get {
                return ResourceManager.GetString("AccountManagementPage_DefaultAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneymanager - Kontoverwaltung.
        /// </summary>
        public static string AccountManagementPageCaption {
            get {
                return ResourceManager.GetString("AccountManagementPageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestehendes Konto entfernen.
        /// </summary>
        public static string AccountManagementRemoveAccountCaption {
            get {
                return ResourceManager.GetString("AccountManagementRemoveAccountCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie wirklich das Konto aus der Liste entfernen? Die Datei wird dabei nicht gelöscht..
        /// </summary>
        public static string AccountManagementRemoveAccountMessage {
            get {
                return ResourceManager.GetString("AccountManagementRemoveAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Kategorie.
        /// </summary>
        public static string CategoryManagementNewCategoryDefaultName {
            get {
                return ResourceManager.GetString("CategoryManagementNewCategoryDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle {0} Monate.
        /// </summary>
        public static string CustomMonthsFormat {
            get {
                return ResourceManager.GetString("CustomMonthsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Öffnen des Konto.
        /// </summary>
        public static string ErrorOpenRecentAccount {
            get {
                return ResourceManager.GetString("ErrorOpenRecentAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:dddd, dd. MMMM yyyy HH:mm}.
        /// </summary>
        public static string LastAccesDateFormat {
            get {
                return ResourceManager.GetString("LastAccesDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.00} €.
        /// </summary>
        public static string MoneyValueFormat {
            get {
                return ResourceManager.GetString("MoneyValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string MonthNameApril {
            get {
                return ResourceManager.GetString("MonthNameApril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string MonthNameAugust {
            get {
                return ResourceManager.GetString("MonthNameAugust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dezember.
        /// </summary>
        public static string MonthNameDecember {
            get {
                return ResourceManager.GetString("MonthNameDecember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Februar.
        /// </summary>
        public static string MonthNameFebuary {
            get {
                return ResourceManager.GetString("MonthNameFebuary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Januar.
        /// </summary>
        public static string MonthNameJanuary {
            get {
                return ResourceManager.GetString("MonthNameJanuary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juli.
        /// </summary>
        public static string MonthNameJuly {
            get {
                return ResourceManager.GetString("MonthNameJuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juni.
        /// </summary>
        public static string MonthNameJune {
            get {
                return ResourceManager.GetString("MonthNameJune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to März.
        /// </summary>
        public static string MonthNameMarch {
            get {
                return ResourceManager.GetString("MonthNameMarch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai.
        /// </summary>
        public static string MonthNameMay {
            get {
                return ResourceManager.GetString("MonthNameMay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string MonthNameNovember {
            get {
                return ResourceManager.GetString("MonthNameNovember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oktober.
        /// </summary>
        public static string MonthNameOctober {
            get {
                return ResourceManager.GetString("MonthNameOctober", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string MonthNameSeptember {
            get {
                return ResourceManager.GetString("MonthNameSeptember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Keine Kategorie&gt;.
        /// </summary>
        public static string NoCategory {
            get {
                return ResourceManager.GetString("NoCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro Monat.
        /// </summary>
        public static string OncePerMonth {
            get {
                return ResourceManager.GetString("OncePerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jedes Halbjahr.
        /// </summary>
        public static string PerHalfYear {
            get {
                return ResourceManager.GetString("PerHalfYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro Quartal.
        /// </summary>
        public static string PerQuarter {
            get {
                return ResourceManager.GetString("PerQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einmal im Jahr.
        /// </summary>
        public static string PerYear {
            get {
                return ResourceManager.GetString("PerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Konto &apos;{0}&apos; wird bereits von einem anderen Programm verwendet. Schließen Sie dieses Programm oder verwenden Sie das bereits geöffnete Programm, um Ihr Konto zu bearbeiten..
        /// </summary>
        public static string RecentAccountLockedFormat {
            get {
                return ResourceManager.GetString("RecentAccountLockedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Konto &apos;{0}&apos; kann nicht gefunden werden.
        ///Möchten Sie den Verweis aus der Liste entfernen?.
        /// </summary>
        public static string RecentAccountNotFoundFormat {
            get {
                return ResourceManager.GetString("RecentAccountNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein unerwarteter Fehler ist aufgetreten: {0}
        ///Kontaktieren Sie den Entwickler..
        /// </summary>
        public static string RecentAccountUnexpectedErrorFormat {
            get {
                return ResourceManager.GetString("RecentAccountUnexpectedErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:dd.MM.yyyy}.
        /// </summary>
        public static string RequestDateFormat {
            get {
                return ResourceManager.GetString("RequestDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:dd. MMMM yyyy}.
        /// </summary>
        public static string RequestDayOfMonthFormat {
            get {
                return ResourceManager.GetString("RequestDayOfMonthFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string RequestDialog_ButtonApply {
            get {
                return ResourceManager.GetString("RequestDialog_ButtonApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string RequestDialog_ButtonCancel {
            get {
                return ResourceManager.GetString("RequestDialog_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schließen.
        /// </summary>
        public static string RequestDialog_ButtonClose {
            get {
                return ResourceManager.GetString("RequestDialog_ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellen.
        /// </summary>
        public static string RequestDialog_ButtonCreate {
            get {
                return ResourceManager.GetString("RequestDialog_ButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaktion anlegen.
        /// </summary>
        public static string RequestDialogCaptionCreate {
            get {
                return ResourceManager.GetString("RequestDialogCaptionCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaktion bearbeiten.
        /// </summary>
        public static string RequestDialogCaptionEdit {
            get {
                return ResourceManager.GetString("RequestDialogCaptionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie einen Betrag an..
        /// </summary>
        public static string RequestDialogViewModel_ValuePropertyValidationError {
            get {
                return ResourceManager.GetString("RequestDialogViewModel_ValuePropertyValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaktion löschen.
        /// </summary>
        public static string RequestManagementDeleteRequestQuestionCaption {
            get {
                return ResourceManager.GetString("RequestManagementDeleteRequestQuestionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sind sie sicher, dass sie den ausgewählten Eintrag löschen möchten?.
        /// </summary>
        public static string RequestManagementDeleteRequestQuestionMessage {
            get {
                return ResourceManager.GetString("RequestManagementDeleteRequestQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programm beenden.
        /// </summary>
        public static string RequestManagementOnClosingRequestConfirmationCaption {
            get {
                return ResourceManager.GetString("RequestManagementOnClosingRequestConfirmationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie das Programm wirklich beenden?.
        /// </summary>
        public static string RequestManagementOnClosingRequestConfirmationMessage {
            get {
                return ResourceManager.GetString("RequestManagementOnClosingRequestConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaktionsverwaltung - {0}.
        /// </summary>
        public static string RequestManagementPageCaptionFormat {
            get {
                return ResourceManager.GetString("RequestManagementPageCaptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dauerauftrag.
        /// </summary>
        public static string StandingOrderDetailsViewModel_ExistingStandingOrderCaption {
            get {
                return ResourceManager.GetString("StandingOrderDetailsViewModel_ExistingStandingOrderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dauerauftrag anlegen.
        /// </summary>
        public static string StandingOrderDetailsViewModel_NewStandingOrderCaption {
            get {
                return ResourceManager.GetString("StandingOrderDetailsViewModel_NewStandingOrderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Unbefristeter Dauerauftrag&gt;.
        /// </summary>
        public static string StandingOrderDialog_NoLastBookDate {
            get {
                return ResourceManager.GetString("StandingOrderDialog_NoLastBookDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiv.
        /// </summary>
        public static string StandingOrderEntityViewModel_StateActive {
            get {
                return ResourceManager.GetString("StandingOrderEntityViewModel_StateActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abgeschlossen.
        /// </summary>
        public static string StandingOrderEntityViewModel_StateFinished {
            get {
                return ResourceManager.GetString("StandingOrderEntityViewModel_StateFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inaktiv.
        /// </summary>
        public static string StandingOrderEntityViewModel_StateInactive {
            get {
                return ResourceManager.GetString("StandingOrderEntityViewModel_StateInactive", resourceCulture);
            }
        }
    }
}
