//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyManagerApplication.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoneyManagerApplication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellen.
        /// </summary>
        public static string AccountManagementPage_CreateCommandCaption {
            get {
                return ResourceManager.GetString("AccountManagementPage_CreateCommandCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zum aktuellen Monat.
        /// </summary>
        public static string AccountManagementPage_GotoCurrentMonthCommandCaption {
            get {
                return ResourceManager.GetString("AccountManagementPage_GotoCurrentMonthCommandCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dateispeicherort.
        /// </summary>
        public static string AccountManagementPage_LabelFilePath {
            get {
                return ResourceManager.GetString("AccountManagementPage_LabelFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AccountManagementPage_LabelName {
            get {
                return ResourceManager.GetString("AccountManagementPage_LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durchsuchen.
        /// </summary>
        public static string AccountManagementPage_OpenAccountCommandCaption {
            get {
                return ResourceManager.GetString("AccountManagementPage_OpenAccountCommandCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffnen.
        /// </summary>
        public static string AccountManagementPage_OpenRecentAccountCommandCaption {
            get {
                return ResourceManager.GetString("AccountManagementPage_OpenRecentAccountCommandCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entfernen.
        /// </summary>
        public static string AccountManagementPage_RemoveAccountCommandCaption {
            get {
                return ResourceManager.GetString("AccountManagementPage_RemoveAccountCommandCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string AccountManagementPage_SelectFileCommandCaption {
            get {
                return ResourceManager.GetString("AccountManagementPage_SelectFileCommandCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neu.
        /// </summary>
        public static string AccountManagementPage_TabItemHeaderNew {
            get {
                return ResourceManager.GetString("AccountManagementPage_TabItemHeaderNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffnen.
        /// </summary>
        public static string AccountManagementPage_TabItemHeaderOpen {
            get {
                return ResourceManager.GetString("AccountManagementPage_TabItemHeaderOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorieverwaltung.
        /// </summary>
        public static string CategoryManagementWindow_Title {
            get {
                return ResourceManager.GetString("CategoryManagementWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halbjährlich.
        /// </summary>
        public static string PeriodName_HalfYearly {
            get {
                return ResourceManager.GetString("PeriodName_HalfYearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monatlich.
        /// </summary>
        public static string PeriodName_Monthly {
            get {
                return ResourceManager.GetString("PeriodName_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro Quartal.
        /// </summary>
        public static string PeriodName_Quarterly {
            get {
                return ResourceManager.GetString("PeriodName_Quarterly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jährlich.
        /// </summary>
        public static string PeriodName_Yearly {
            get {
                return ResourceManager.GetString("PeriodName_Yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwerfen.
        /// </summary>
        public static string RegularyRequestDialog_Cancel {
            get {
                return ResourceManager.GetString("RegularyRequestDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie.
        /// </summary>
        public static string RegularyRequestDialog_Category {
            get {
                return ResourceManager.GetString("RegularyRequestDialog_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schließen.
        /// </summary>
        public static string RegularyRequestDialog_Close {
            get {
                return ResourceManager.GetString("RegularyRequestDialog_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        public static string RegularyRequestDialog_Delete {
            get {
                return ResourceManager.GetString("RegularyRequestDialog_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        public static string RegularyRequestDialog_Description {
            get {
                return ResourceManager.GetString("RegularyRequestDialog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        public static string RegularyRequestDialog_Edit {
            get {
                return ResourceManager.GetString("RegularyRequestDialog_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erste Buchung.
        /// </summary>
        public static string RegularyRequestDialog_FirstBookDate {
            get {
                return ResourceManager.GetString("RegularyRequestDialog_FirstBookDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        public static string RegularyRequestDialog_GridColmnHeader_Description {
            get {
                return ResourceManager.GetString("RegularyRequestDialog_GridColmnHeader_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervall.
        /// </summary>
        public static string RegularyRequestDialog_GridColmnHeader_MonthPeroid {
            get {
                return ResourceManager.GetString("RegularyRequestDialog_GridColmnHeader_MonthPeroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betrag.
        /// </summary>
        public static string RegularyRequestDialog_GridColmnHeader_Value {
            get {
                return ResourceManager.GetString("RegularyRequestDialog_GridColmnHeader_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neu.
        /// </summary>
        public static string RegularyRequestDialog_New {
            get {
                return ResourceManager.GetString("RegularyRequestDialog_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervall.
        /// </summary>
        public static string RegularyRequestDialog_Period {
            get {
                return ResourceManager.GetString("RegularyRequestDialog_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string RegularyRequestDialog_Save {
            get {
                return ResourceManager.GetString("RegularyRequestDialog_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betrag.
        /// </summary>
        public static string RegularyRequestDialog_Value {
            get {
                return ResourceManager.GetString("RegularyRequestDialog_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellen.
        /// </summary>
        public static string RequestDialog_CreateCommandCaption {
            get {
                return ResourceManager.GetString("RequestDialog_CreateCommandCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie.
        /// </summary>
        public static string RequestDialog_LabelCategory {
            get {
                return ResourceManager.GetString("RequestDialog_LabelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag des Monats.
        /// </summary>
        public static string RequestDialog_LabelDayOfMonth {
            get {
                return ResourceManager.GetString("RequestDialog_LabelDayOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        public static string RequestDialog_LabelDescription {
            get {
                return ResourceManager.GetString("RequestDialog_LabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betrag.
        /// </summary>
        public static string RequestDialog_LabelValue {
            get {
                return ResourceManager.GetString("RequestDialog_LabelValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie.
        /// </summary>
        public static string RequestManagementPage_DataGridColumnCategory {
            get {
                return ResourceManager.GetString("RequestManagementPage_DataGridColumnCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string RequestManagementPage_DataGridColumnDate {
            get {
                return ResourceManager.GetString("RequestManagementPage_DataGridColumnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        public static string RequestManagementPage_DataGridColumnDescription {
            get {
                return ResourceManager.GetString("RequestManagementPage_DataGridColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betrag.
        /// </summary>
        public static string RequestManagementPage_DataGridColumnValue {
            get {
                return ResourceManager.GetString("RequestManagementPage_DataGridColumnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monatssaldo.
        /// </summary>
        public static string RequestManagementPage_LabelMonthSaldo {
            get {
                return ResourceManager.GetString("RequestManagementPage_LabelMonthSaldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string Window_CancelCommandCaption {
            get {
                return ResourceManager.GetString("Window_CancelCommandCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Window_OkCommandCaption {
            get {
                return ResourceManager.GetString("Window_OkCommandCaption", resourceCulture);
            }
        }
    }
}
