//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyManagerApplication.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoneyManagerApplication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoneyManager 2015.
        /// </summary>
        public static string AccountManagementPage_ApplicationTitle {
            get {
                return ResourceManager.GetString("AccountManagementPage_ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright Peter Friedland.
        /// </summary>
        public static string AccountManagementPage_CopyRightDeveloper {
            get {
                return ResourceManager.GetString("AccountManagementPage_CopyRightDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier können Sie ein neues Konto anlegen. Geben Sie einen Namen ein, wählen Sie einen Speicherort und klicken sie dann auf Erstellen..
        /// </summary>
        public static string AccountManagementPage_CreateAccountDescription {
            get {
                return ResourceManager.GetString("AccountManagementPage_CreateAccountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellen.
        /// </summary>
        public static string AccountManagementPage_CreateCommandCaption {
            get {
                return ResourceManager.GetString("AccountManagementPage_CreateCommandCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Josephine Rosin.
        /// </summary>
        public static string AccountManagementPage_DesignRight {
            get {
                return ResourceManager.GetString("AccountManagementPage_DesignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zum aktuellen Monat.
        /// </summary>
        public static string AccountManagementPage_GotoCurrentMonthCommandCaption {
            get {
                return ResourceManager.GetString("AccountManagementPage_GotoCurrentMonthCommandCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dateispeicherort.
        /// </summary>
        public static string AccountManagementPage_LabelFilePath {
            get {
                return ResourceManager.GetString("AccountManagementPage_LabelFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AccountManagementPage_LabelName {
            get {
                return ResourceManager.GetString("AccountManagementPage_LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Konten gefunden. Erstellen Sie zuerst ein Konto oder verwenden Sie durchsuchen, um Ihr Konto auszuwählen. Diese Konten werden danach hier zum sofortigen Öffnen angezeigt..
        /// </summary>
        public static string AccountManagementPage_NoRecentAccountsDescription {
            get {
                return ResourceManager.GetString("AccountManagementPage_NoRecentAccountsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durchsuchen.
        /// </summary>
        public static string AccountManagementPage_OpenAccountCommandCaption {
            get {
                return ResourceManager.GetString("AccountManagementPage_OpenAccountCommandCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffnen.
        /// </summary>
        public static string AccountManagementPage_OpenRecentAccountCommandCaption {
            get {
                return ResourceManager.GetString("AccountManagementPage_OpenRecentAccountCommandCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entfernen.
        /// </summary>
        public static string AccountManagementPage_RemoveAccountCommandCaption {
            get {
                return ResourceManager.GetString("AccountManagementPage_RemoveAccountCommandCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string AccountManagementPage_SelectFileCommandCaption {
            get {
                return ResourceManager.GetString("AccountManagementPage_SelectFileCommandCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neu.
        /// </summary>
        public static string AccountManagementPage_TabItemHeaderNew {
            get {
                return ResourceManager.GetString("AccountManagementPage_TabItemHeaderNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffnen.
        /// </summary>
        public static string AccountManagementPage_TabItemHeaderOpen {
            get {
                return ResourceManager.GetString("AccountManagementPage_TabItemHeaderOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neu.
        /// </summary>
        public static string CategoryManagementWindow_ButtonNew {
            get {
                return ResourceManager.GetString("CategoryManagementWindow_ButtonNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorieverwaltung.
        /// </summary>
        public static string CategoryManagementWindow_Title {
            get {
                return ResourceManager.GetString("CategoryManagementWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seit dem Sie das letzten Mal Ihre Finanzen verwaltet haben sind folgende Daueraufträge automatisch für Sie eingetragen worden:.
        /// </summary>
        public static string CreatedRequestDialog_Description {
            get {
                return ResourceManager.GetString("CreatedRequestDialog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willkommen zurück!.
        /// </summary>
        public static string CreatedRequestDialog_Title {
            get {
                return ResourceManager.GetString("CreatedRequestDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startinformation.
        /// </summary>
        public static string CreatedRequestDialog_WindowTitle {
            get {
                return ResourceManager.GetString("CreatedRequestDialog_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halbjährlich.
        /// </summary>
        public static string PeriodName_HalfYearly {
            get {
                return ResourceManager.GetString("PeriodName_HalfYearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monatlich.
        /// </summary>
        public static string PeriodName_Monthly {
            get {
                return ResourceManager.GetString("PeriodName_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro Quartal.
        /// </summary>
        public static string PeriodName_Quarterly {
            get {
                return ResourceManager.GetString("PeriodName_Quarterly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle 2 Monate.
        /// </summary>
        public static string PeriodName_TwoMonthly {
            get {
                return ResourceManager.GetString("PeriodName_TwoMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jährlich.
        /// </summary>
        public static string PeriodName_Yearly {
            get {
                return ResourceManager.GetString("PeriodName_Yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie.
        /// </summary>
        public static string RequestDialog_LabelCategory {
            get {
                return ResourceManager.GetString("RequestDialog_LabelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag des Monats.
        /// </summary>
        public static string RequestDialog_LabelDayOfMonth {
            get {
                return ResourceManager.GetString("RequestDialog_LabelDayOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        public static string RequestDialog_LabelDescription {
            get {
                return ResourceManager.GetString("RequestDialog_LabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art.
        /// </summary>
        public static string RequestDialog_LabelRequestKind {
            get {
                return ResourceManager.GetString("RequestDialog_LabelRequestKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betrag.
        /// </summary>
        public static string RequestDialog_LabelValue {
            get {
                return ResourceManager.GetString("RequestDialog_LabelValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einnahme.
        /// </summary>
        public static string RequestKindName_Earning {
            get {
                return ResourceManager.GetString("RequestKindName_Earning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgabe.
        /// </summary>
        public static string RequestKindName_Expenditure {
            get {
                return ResourceManager.GetString("RequestKindName_Expenditure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuer Eintrag.
        /// </summary>
        public static string RequestManagementPage_AddRequest {
            get {
                return ResourceManager.GetString("RequestManagementPage_AddRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie.
        /// </summary>
        public static string RequestManagementPage_DataGridColumnCategory {
            get {
                return ResourceManager.GetString("RequestManagementPage_DataGridColumnCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string RequestManagementPage_DataGridColumnDate {
            get {
                return ResourceManager.GetString("RequestManagementPage_DataGridColumnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        public static string RequestManagementPage_DataGridColumnDescription {
            get {
                return ResourceManager.GetString("RequestManagementPage_DataGridColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betrag.
        /// </summary>
        public static string RequestManagementPage_DataGridColumnValue {
            get {
                return ResourceManager.GetString("RequestManagementPage_DataGridColumnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorien verwalten.
        /// </summary>
        public static string RequestManagementPage_EditCategories {
            get {
                return ResourceManager.GetString("RequestManagementPage_EditCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eintrag bearbeiten.
        /// </summary>
        public static string RequestManagementPage_EditRequest {
            get {
                return ResourceManager.GetString("RequestManagementPage_EditRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daueraufträge verwalten.
        /// </summary>
        public static string RequestManagementPage_EditStandingOrders {
            get {
                return ResourceManager.GetString("RequestManagementPage_EditStandingOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umsätze auswählen.
        /// </summary>
        public static string RequestManagementPage_HeadingChooseSaldos {
            get {
                return ResourceManager.GetString("RequestManagementPage_HeadingChooseSaldos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monatssaldo.
        /// </summary>
        public static string RequestManagementPage_LabelMonthSaldo {
            get {
                return ResourceManager.GetString("RequestManagementPage_LabelMonthSaldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeitraum.
        /// </summary>
        public static string RequestManagementPage_Period {
            get {
                return ResourceManager.GetString("RequestManagementPage_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eintrag löschen.
        /// </summary>
        public static string RequestManagementPage_RemoveRequest {
            get {
                return ResourceManager.GetString("RequestManagementPage_RemoveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konto wechseln.
        /// </summary>
        public static string RequestManagementPage_SwitchAccount {
            get {
                return ResourceManager.GetString("RequestManagementPage_SwitchAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heute.
        /// </summary>
        public static string RequestManagementPage_Today {
            get {
                return ResourceManager.GetString("RequestManagementPage_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl der Buchungen.
        /// </summary>
        public static string StandingOrderDialog_BookCount {
            get {
                return ResourceManager.GetString("StandingOrderDialog_BookCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buchungen.
        /// </summary>
        public static string StandingOrderDialog_BookingCount {
            get {
                return ResourceManager.GetString("StandingOrderDialog_BookingCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwerfen.
        /// </summary>
        public static string StandingOrderDialog_Cancel {
            get {
                return ResourceManager.GetString("StandingOrderDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie.
        /// </summary>
        public static string StandingOrderDialog_Category {
            get {
                return ResourceManager.GetString("StandingOrderDialog_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schließen.
        /// </summary>
        public static string StandingOrderDialog_Close {
            get {
                return ResourceManager.GetString("StandingOrderDialog_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        public static string StandingOrderDialog_Delete {
            get {
                return ResourceManager.GetString("StandingOrderDialog_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        public static string StandingOrderDialog_Description {
            get {
                return ResourceManager.GetString("StandingOrderDialog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        public static string StandingOrderDialog_Edit {
            get {
                return ResourceManager.GetString("StandingOrderDialog_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Befristet:.
        /// </summary>
        public static string StandingOrderDialog_EndingTransaction {
            get {
                return ResourceManager.GetString("StandingOrderDialog_EndingTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buchung ab.
        /// </summary>
        public static string StandingOrderDialog_FirstBookDate {
            get {
                return ResourceManager.GetString("StandingOrderDialog_FirstBookDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        public static string StandingOrderDialog_GridColmnHeader_Description {
            get {
                return ResourceManager.GetString("StandingOrderDialog_GridColmnHeader_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervall.
        /// </summary>
        public static string StandingOrderDialog_GridColmnHeader_MonthPeroid {
            get {
                return ResourceManager.GetString("StandingOrderDialog_GridColmnHeader_MonthPeroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zustand.
        /// </summary>
        public static string StandingOrderDialog_GridColmnHeader_State {
            get {
                return ResourceManager.GetString("StandingOrderDialog_GridColmnHeader_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betrag.
        /// </summary>
        public static string StandingOrderDialog_GridColmnHeader_Value {
            get {
                return ResourceManager.GetString("StandingOrderDialog_GridColmnHeader_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letzte Buchung.
        /// </summary>
        public static string StandingOrderDialog_LastBooking {
            get {
                return ResourceManager.GetString("StandingOrderDialog_LastBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neu.
        /// </summary>
        public static string StandingOrderDialog_New {
            get {
                return ResourceManager.GetString("StandingOrderDialog_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervall.
        /// </summary>
        public static string StandingOrderDialog_Period {
            get {
                return ResourceManager.GetString("StandingOrderDialog_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string StandingOrderDialog_Save {
            get {
                return ResourceManager.GetString("StandingOrderDialog_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betrag.
        /// </summary>
        public static string StandingOrderDialog_Value {
            get {
                return ResourceManager.GetString("StandingOrderDialog_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daueraufträge verwalten.
        /// </summary>
        public static string StandingOrders_ChooseStandingOrder {
            get {
                return ResourceManager.GetString("StandingOrders_ChooseStandingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abgeschlossene Aufträge anzeigen.
        /// </summary>
        public static string StandingOrders_ShowFinishedStandingOrders {
            get {
                return ResourceManager.GetString("StandingOrders_ShowFinishedStandingOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daueraufträge verwalten.
        /// </summary>
        public static string StandingOrders_WindowTitle {
            get {
                return ResourceManager.GetString("StandingOrders_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string Window_CancelCommandCaption {
            get {
                return ResourceManager.GetString("Window_CancelCommandCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Window_OkCommandCaption {
            get {
                return ResourceManager.GetString("Window_OkCommandCaption", resourceCulture);
            }
        }
    }
}
